sudo: false
language: node_js
node_js:
  - "node"
  - "11.6"
  - "10.11"
  - "9.11"
  - "8.12"
  - "7.10"
  - "6.14"
cache:
  directories:
    - "node_modules"
install:
  - npm install
script:
  - npm test
