name: release

# Allow to trigger this workflow manually and enter a release version to release
# See: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/
on:
    workflow_dispatch:
        inputs:
            releaseVersion:
                description: "Release tag version"
                required: true

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2
              with:
                  ref: "master"
                  fetch-depth: 0
            - uses: oleksiyrudenko/gha-git-credentials@v2-latest
              with:
                  token: "${{ secrets.GITHUB_TOKEN }}"
            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 22
                  registry-url: https://registry.npmjs.org
            - name: Release version
              run: npx -p @release-it/bumper@6.0.1 -p auto-changelog -p release-it@17.11.0 release-it --verbose --increment ${{ github.event.inputs.releaseVersion }}
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
                  GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
