name: run-tests

on: [push]

jobs:
    tests:
        strategy:
            fail-fast: true
            matrix:
                node: ["18", "20", "22"] # https://nodejs.org/en/about/releases/
        name: NPM test - (Node ${{ matrix.node }})
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - uses: actions/setup-node@v2-beta
              with:
                  node-version: ${{ matrix.node }}
            - name: Install dependencies
              run: npm ci
            - name: Run tests
              run: npm test
